TARGET=Darwin
EXECUTABLE = executable_$(TARGET)
BUILD_PATH=./build/osx
CXXFLAGS= -w \
	  -std=c++0x \
	  -F "./frameworks/osx" \
	  -DTARGET_OS_MAC

LDFLAGS = -framework SDL2 \
	-framework SDL2_image \
	-framework SDL2_mixer \
	-framework SDL2_net \
	-framework SDL2_ttf \
	-framework Box2D
