TARGET=Linux
EXECUTABLE = executable_$(TARGET)
BUILD_PATH=./build/linux

CXXFLAGS= -w \
	-std=c++0x

LDFLAGS = -lSDL2main \
	-lSDL2 \
	-lSDL2_image \
	-lSDL2_mixer \
	-lSDL2_ttf \
	-lSDL2_net \
	-lbox2d \
	-I/usr/include
